version: "3.7"
services:
  app:
    build: .
    image: abiodunjames/example-app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app/
    ports:
      - 80:8000
    environment:
      - DATABASE_URI=sqlite:///test.db
      - DOMAIN_NAME=http://localhost:8000